Backend link to Frontend
rodrigomv29/squidward-cs490-group-project pull request #35
Opened 2023-07-05 13:40 UTC by ronaldcohen1611

Linking of backend API and database to frontend logic and components. Api calls are now being safeguarded by ArticleHandler and queried by ArticleDistobutor for suitable use in the frontend.

2023-07-05 16:39 UTC, chrism1001 commented
![image](https://github.com/rodrigomv29/squidward-cs490-group-project/assets/58187990/a064b309-cf01-49f8-a016-a8de83758e99)
currently getting this error

2023-07-05 16:43 UTC, chrism1001 commented on web/src/components/SlidingPanel/SlidingPanel.tsx
![image](https://github.com/rodrigomv29/squidward-cs490-group-project/assets/58187990/2cbc82be-596c-41f7-97fd-7501ababda04)

2023-07-05 16:44 UTC, chrism1001 requested changes
Getting an error for categoriesArticlesMap being undefined in categorieslistitems.tsx and slidingpanel.tsx

2023-07-06 00:15 UTC, rodrigomv29 commented
I am taking a look right now

2023-07-06 00:55 UTC, rodrigomv29 commented
Did you guys run `yarn rw prisma migrate dev`

2023-07-06 01:06 UTC, rodrigomv29 reviewed
Works fine for me right now. Just remember that for every change to the schema we have to migrate

2023-07-06 02:02 UTC, rodrigomv29 commented
I saw the new changes now.... now we have a problem with dbAuth

2023-07-06 02:03 UTC, rodrigomv29 commented
I think we need to generate a new secret

2023-07-06 02:04 UTC, rodrigomv29 commented
I think the command is yarn rw g secret

2023-07-06 02:04 UTC, rodrigomv29 commented
`yarn rw g secret`

2023-07-06 06:42 UTC, ronaldcohen1611 commented on web/src/components/SlidingPanel/SlidingPanel.tsx
I was able to fix those bugs with optional chaining for all the pages.

2023-07-06 06:44 UTC, ronaldcohen1611 commented
I was able to go through and fix most of the page rendering bugs, verifying by simulating clone down onto new machine by using my desktop. It should be good to go now.
![image](https://github.com/rodrigomv29/squidward-cs490-group-project/assets/110629268/ea034176-0514-4514-a450-2fa705ff5feb)

2023-07-06 16:45 UTC, rodrigomv29 commented
<img width="917" alt="new-homepage" src="https://github.com/rodrigomv29/squidward-cs490-group-project/assets/43789876/5a211072-a4c7-4f6d-9fbf-f3d0fbce1572">

2023-07-06 16:59 UTC, rodrigomv29 commented
<img width="938" alt="dark-mode-homepage" src="https://github.com/rodrigomv29/squidward-cs490-group-project/assets/43789876/1c096e5c-6dc8-42a5-b40c-e896fc1939ea">

2023-07-06 19:33 UTC, Ballslamic commented on api/db/schema.prisma
Changed authentication requirements for mapping errors.

2023-07-06 19:34 UTC, Ballslamic commented on api/src/graphql/articles.sdl.ts
Changed authentication requirements for mapping + loading errors.

2023-07-06 19:34 UTC, Ballslamic commented on api/src/graphql/categories.sdl.ts
Changed authentication requirements for mapping errors.

2023-07-06 19:37 UTC, Ballslamic commented
Went through the site for:
- Logged-in and logged-out, light/dark theme, all nav options + search work; as well as redirection to the actual article site.

2023-07-07 13:26 UTC, chrism1001 approved these changes
Thank you for fixing the errors. Works fine on my end.

2023-07-07 14:00 UTC, merged